import React from 'react'

const Terms = () => {
  return (
    <div>
      <h1>Terms</h1>
      <p>
        This document is an electronic record in terms of Information Technology
        Act, 2000 and rules there under as applicable and the amended provisions
        pertaining to electronic records in various statutes as amended by the
        Information Technology Act, 2000. This electronic record is generated by
        a computer system and does not require any physical or digital
        signatures.
      </p>
    </div>
  )
}

export default Terms
